### PR TITLE
feat: support multiple controllers with same namespace

### LINKED ISSUE #535: feature: allow multiple controllers to use the same dynamic namespace
### Description
Currently we cannot use the same namespace for multiple controllers because the connection event only fires once for a dynamic namespace even if we have multiple listeners.

We should be able to register multiple controllers witht the exact same namespace.

### PR DESCRIPTION
**Pull request by attilaorosz**
## Description
Support registering multiple controllers to the same namespace

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [ ] documentation added or updated
- [x] I have run the project locally and verified that there are no errors

### Fixes

fixes #535

### CODE REVIEW

**Comment by sudharsan-selvaraj** [comment]
@attilaorosz I just started using socket-controllers in my project and this feature is something i'm looking for. When can i expected it to be released to npm registry?

**Comment by attilaorosz** [comment]
Hi, I’ll try to make a release today.

**Comment by sudharsan-selvaraj** [comment]
@attilaorosz Awesome. Thanks for the swift response and much appreciated!

**Comment by attilaorosz** [comment]
@sudharsan-selvaraj Release is done, let me know if something is not correct.

**Pull request merged**
