### PR TITLE
Major release

### PR DESCRIPTION
**Pull request by rustamwin**

### CODE REVIEW

**Comment by GabeKuslansky** [comment]
The current user checker would be incredibly useful in a project I am working on currently. Can that be merged soon, if possible?

**Comment by rustamwin** [comment]
I hope I will have free time for this next year.

**Comment by GabeKuslansky** [comment]
> I hope I will have free time for this next year.

Any chance of this getting merged soon?

**Comment by NoNameProvided** [comment]
Hi @rustamwin! The project tooling and formatting has been updated. You will need to recreate this PR with only the changes related to the library.

**Comment by NoNameProvided** [comment]
Closing as out-of-date. I suggest recreating this in a new PR where only the relevant code changes are included.

**Pull request closed without merging**
