### PR TITLE
fix: Cannot read property 'filter' of undefined

### LINKED ISSUE #216: fix: if controllers array is empty or undefined i have error "Cannot read property 'filter' of undefined"
### Description

When i use useSocketServer(io) without controllers array in options i have error "Cannot read property 'filter' of undefined"
**Minimal code-snippet showcasing the problem**
 

```ts
useSocketServer(io);
```
In src/index.js:36
```ts
if (options && options.controllers && options.controllers.length)
    controllerClasses = (options.controllers as any[]).filter(controller => controller instanceof Function);
  const controllerDirs = (options.controllers as any[]).filter(controller => typeof controller === 'string');
  controllerClasses.push(...importClassesFromDirectories(controllerDirs));
```
please, add scopes for if
### Expected behavior

doesnt get error
### Actual behavior

get error

### PR DESCRIPTION
**Pull request by alexgev**
Fixes 
## Description
if controllers array is empty or undefined i have error "Cannot read property 'filter' of undefined"

## Checklist

- [x] the pull request title describes what this PR does (not a vague title like `Update index.md`)
- [x] the pull request targets the *default* branch of the repository (`develop`)
- [x] the code follows the established code style of the repository
  - `npm run prettier:check` passes
  - `npm run lint:check` passes
- [x] tests are added for the changes I made (if any source code was modified)
- [ ] documentation added or updated
- [ ] I have run the project locally and verified that there are no errors

### Fixes

fixes #216

### CODE REVIEW

**Comment by NoNameProvided** [comment]
Hi! 

Thanks for the PR, please add a test case for this as well, so we know it won' be re-introduced later.

**Comment by alexgev** [comment]
Hi!
I'm glad to help you. Tests have been added.

**Comment by Blargian** [comment]
Hey everyone, was this ever fixed? I'm getting the same error still when calling useSocketServer without the controllers array.

**Review by rustamwin — APPROVED** [review]
Could you please resolve conflicts? Thanks.

**Comment by attilaorosz** [comment]
@alexgev Sorry for the late action on this. I've included your fix and test in another PR. Thanks again!

**Pull request closed without merging**
