### PR TITLE
docs: Fix table not working on Decorators Reference

### PR DESCRIPTION
**Pull request by gentritabazi01**
## Description

This pr fix Decorators Reference table that not showing as well in ReadMe.

### CODE REVIEW

**Comment by gentritabazi01** [comment]
@NoNameProvided

**Review by rustamwin — APPROVED** [review]

**Comment by gentritabazi01** [comment]
@rustamwin Can you merge ?!

**Comment by gentritabazi01** [comment]
@rustamwin @NoNameProvided

**Comment by rustamwin** [comment]
Wierd, github says "this branch is out-of-date with the base branch"
image

**Pull request closed without merging**
